### ISSUE TITLE
Tensor shape error

### ISSUE THREAD

**Issue by persistz** [nesl/adversarial_genattack#2]
When run MNIST attacks, it is easy to get an error about:
ValueError: Cannot convert a partially known TensorShape to a Tensor: <unknown>

It can be triggered by:
xover_prop = tf.cast(tf.random_uniform(shape=parent1.get_shape()) > pp2, tf.float32)
OR:
    def mutation_op(self,  cur_pop, idx, step_noise=0.01, p=0.005):
        perturb_noise = tf.random_uniform(cur_pop.get_shape(),
            minval=-step_noise, maxval=step_noise, dtype=tf.float32)
        mutated_pop = perturb_noise * tf.cast(tf.random_uniform(cur_pop.get_shape()) < p, tf.float32) + cur_pop
        return mutated_pop

I think the reason is when use inception to do prediction, a value with specific shape(shown below) can be returned:
predict input: Tensor("while/clip_by_value:0", shape=(6, 299, 299, 3), dtype=float32)
predict output: Tensor("while/import/InceptionV3/Predictions/Softmax:0", shape=(6, 1001), dtype=float32)

But when use MNIST keras model, only (?, 10) can be returned:
predict input: Tensor("while/clip_by_value:0", shape=(4, 28, 28, 1), dtype=float32)
predict output shape: (?, 10)

**Comment by malzantot** [comment]
Thanks for your report.
 Which version of TensorFlow and Keras are you using ?
The code works without shape errors while using TensorFlow ('1.14.0') and Keras ('2.2.4').

**Comment by persistz** [comment]
OK, my version of TensorFlow and Keras is 1.12 and 2.1.3.
I will update my repos and test again then close this question.
Thanks for your reply.
